### ISSUE TITLE
Not compatible with tt-rss v1.12 

### ISSUE THREAD

**Issue by timendum** [idoxlr8/article_toolbar#3]
Hi,
today a new version of Tiny Tiny RSS v1.12 has been released and this fabulous plug-in is not compatible with the new version of the UI.

(Maybe i can work on it.)

**Comment by idoxlr8** [comment]
Please be my guest, I have been busy but I will look into it tomorrow, thanks for bringing this to my attention.

**Comment by tschinz** [comment]
It works if you use the [reeder theme](https://github.com/tschinz/tt-rss_reeder_theme), if the problem is GUI related. The functions work in my ttrss v1.12 version.
